### About reduce_mean 

The functionality of numpy.mean and tensorflow.reduce_mean are the *same*

In [0]:
import numpy as np
import tensorflow as tf

In [2]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(c)

[[3. 4.]
 [5. 6.]
 [6. 7.]]


In [3]:
m1 = np.mean(c, 1) # same as 'm1 = np.mean(c, axis = 1)' axis는 방향을 지정해 주는 것 1이면 가로 0이면 세로
print(m1)

[3.5 5.5 6.5]


In [4]:
m2 = tf.reduce_mean(c,1) # same as 'm2 = tf.reduce_mean(c, axis = 1)' reduce_mean은 평균을 구하는 것이다.
with tf.Session() as sess:
    result = sess.run(m2)
    print(result)

[3.5 5.5 6.5]
